# 应用环境配置
solon.env: @profiles.active@

# security url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login
    - /swagger/v2
    - /test/user/**

--- ## 加载common项目配置文件
solon.config.load: "config/*.yml"