# 应用环境配置
solon.env: @profiles.active@

# 加载配置
solon.config.load: "config/layjava-*.yml"

# 缓存配置 (caffeine/redis)
layjava.cache:
  driverType: redis
  server: 10.0.0.16:6379
  defSeconds: 30

# url放行配置
security:
  # 排除路径
  excludes:
    - /
    # 登录
    - /auth/login
    - /swagger/v2
    - /test/user/**
    - /cache

